pool:
  vmImage: 'ubuntu-24.04'

steps:
- checkout: self

- script: |
    set -e
    #sudo apt install libbz2-dev libarchive-dev

    #cd mt-comp-test
    sh ./1-prep.sh
    sh ./2-test.sh
  displayName: 'Run prep and test scripts'
